### ISSUE TITLE
Adding id attribute to flash-alert div tag causes flash to not show

### ISSUE THREAD

**Issue by BrianHutchison** [wmluke/angular-flash#14]
Adding an id attribute to the flash-alert div tag causes flash to not show. For example, the following will not work:

```
<!-- Set the display duration in milli-secs.  Default is 5000, 0 disables the fade-away. -->
<div flash-alert id="alerts" active-class="in" class="alert fade" duration="0">
    <!-- Manually hide the alert with `hide()` -->
    <button type="button" class="close" ng-click="hide()">&times;</button>
    <strong class="alert-heading">Boo!</strong>
    <span class="alert-message">{{flash.message}}</span>
</div>
```

Expected/desired behavior is that the id tag can be added without causing any change in behavior. I've tried it both near the beginning of the attributes as shown above and at the end.

**Comment by wmluke** [comment]
Hi @BrianHutchison,

This is due to a new feature in [release 0.1.9](https://github.com/wmluke/angular-flash/releases/tag/0.1.9) that allows sending flashes to named subscribers.  

In retrospect, I probably should have incremented to the next minor version (0.2.0) to avoid breaking changes. Unfortunately, at this point the cat-is-out-of-the-bag, and mucking with the versioning could cause more havoc.

Given your template, you can send flashes to element `#alerts` like so...

``` javascript
flash.to('alerts').success = 'Nice work!';
```
